### ISSUE TITLE
Update Epic titles to represent WHY not what

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1215]
## Description
- [x] gather a list of all Epics
- [x] Create a [spreadsheet](https://docs.google.com/spreadsheets/d/1pqAmYppD3j1PQYvq9ueZyKgxpxjwT_-ulZagTEFXvYg/edit#gid=0) with old name and new name (WHY we are doing this epic)
   - Some epics might become multiple epics
- [x] @msdisme review spreadsheet and suggested names
- [x] @msdisme assign back to @joachimweyl for non-esi items
- [x] @joachimweyl update Epics based on new titles
- [x] @joachimweyl update Epic GH issue template
   - Epic title is a WHY
   - include how to create ZH epic
- [x] @joachimweyl update Epic links to match new link rule

## Completion dates
Desired - 2024-01-10
Required - TBD

**Comment by joachimweyl** [comment]
@msdisme the [sheet](https://docs.google.com/spreadsheets/d/1pqAmYppD3j1PQYvq9ueZyKgxpxjwT_-ulZagTEFXvYg/edit?pli=1#gid=0) is ready for your review of new names.
