### ISSUE TITLE
Tracking Issue for R4PA power switchboard work

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1293]
Note from John Goodhue and Wayne: 
```
To Continue the Switchboard testing that was discussed
in the Program Management Group meetings

We are hoping to do this work on Thursday/Friday, April 25-26.  Would that be possible?

The switchboard test will affect both the even side and the odd side of Pod 4A.  We will
will take down the A side bus bars on one day, and the B side bus bars on the other day,
with power up on both sides over night.

```
Our preference would be to wait until after end of classes on May 1. 

We are affected by R4PA which includes IDRACs, CEPH HW,  ESI controllers, switches and some MOC related servers running processes.     We do not expect an outage, but in an abundance of caution we are doing the following:

- [x] Hakan confirming the systems in the rack are set up properly for power bars.  
- [x] Hakan to note exceptions to bus bars - eg. some single power switches?
- [x] Identify impact of any of those - eg. we have a lot of development work going on based on ESI
- [x] Notify OKDMoca users
- [x] Notify CEPH research users
- [x] Confirm OpenStack Billing does not have dependencies @knikolla

**Comment by knikolla** [comment]
OpenStack billing only has a dependency on `nerc-shift-0`, so I'm checking the last checkbox.

**Comment by joachimweyl** [comment]
@msdisme it sounds like this is complete.
