### ISSUE TITLE
Organize Roadmap

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1388]
## Motivation
updates requested by Wayne

## Completion Criteria
changes below completed

## Description
- [x] Clear out Project only rows
- [x] Update Original order
- [x] Update From What List column
- [x] sort by Date Required By
- [x] move all items currently being worked on above line
- [x] add new epics added to ZenHub
## Completion dates
Desired - 2024-09-19
Required - 2024-09-23 11am
