### ISSUE TITLE
Roadmap updates

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1389]
## Motivation
updates requested in Strat meeting

## Completion Criteria
complete all requests from strat meeting

## Description
- [x] Add notes column
- [x] Update dates above the line
- [x] Update links above the line
- [x] Update links below the line
- [x] Send out [When2meet](https://www.when2meet.com/?26634384-ZiJxh)

## Completion dates
Desired - 2024-09-25
Required - 2024-09-27
