### ISSUE TITLE
Update Roadmap - phase 3

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1397]
## Description
- [x] update Zenhub based on changes
- [x] update spreadsheet with "Engineers involved" column
- [x] update spreadsheet with "current story points" column
- [x] update spreadsheet with "percentage of complete" column
- [x] update spreadsheet with "how sure we are we don’t need more issues added to epic" column

## Completion dates
Desired - 2024-12-04
Required - TBD
