### ISSUE TITLE
Roadmap Revamp

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1405]
## Motivation
implement new priorities based on [document](https://docs.google.com/document/d/1J1RkARWmxk749T34ONICMpl5ihcqVU0NJ95LwmbBByQ/edit?usp=sharing)

## Completion Criteria
new column for Roadmap [Spreadsheet](https://docs.google.com/spreadsheets/d/1Hzcecy5mrZtanjhBn5zBfb49B6PoyyIa-sDTy1qnAvY/edit?usp=sharing) and sort based on document above

## Description
- [x] Add Roadmap Name Column
- [x] Update Roadmap Name Column
- [x] Schedule meeting to review with Michael and Wayne

## Completion dates
Desired - 2024-10-22
Required - TBD
