### ISSUE TITLE
Roadmap Revamp 2

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1418]
## Motivation
implement new priorities based on [document](https://docs.google.com/document/d/1J1RkARWmxk749T34ONICMpl5ihcqVU0NJ95LwmbBByQ/edit?usp=sharing) & meeting with Miachel & Wayne

## Completion Criteria
Pepare Roadmap [Spreadsheet](https://docs.google.com/spreadsheets/d/1Hzcecy5mrZtanjhBn5zBfb49B6PoyyIa-sDTy1qnAvY/edit?usp=sharing) based on meeting decisions and schedule a meeting with the whole group.

## Description
- [x] Sort based on priorities in the document above
- [x] Discuss new ways to organize epics and projects to more closely match Roadmap
- [x] Schedule meeting with whole group

## Completion dates
Desired - 2024-11-13
Required - TBD
