### ISSUE TITLE
Convert MOC to NERC Migration Documentation to Markdown and upload to NERC Documentation

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#539]
- [x] Convert document created in this issue #509 to Markdown
- [x] Upload to [NERC documentation](https://nerc-project.github.io/nerc-docs/openstack/migration-from-MOC-to-NERC/Step1/)
- [x] Convert document created in this issue #510 to Markdown
- [x] Upload to [NERC documentation](https://nerc-project.github.io/nerc-docs/openstack/migration-from-MOC-to-NERC/Step2/)
- [x] Convert document created in this issue #511 to Markdown
- [x] [PR](https://github.com/nerc-project/nerc-docs/pull/55) submitted

**Comment by joachimweyl** [comment]
PR submitted, all documents converted to Markdown.
